steps:
  # Build the Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/global-mobility-services/testingsanty', 'serverless-shell-scripts/.']

  # Push the image to GCR.IO.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/global-mobility-services/testingsanty']

# Replace $PROJECT_ID with your actual Google Cloud project ID.
