steps:
  # Build the Docker image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/global-mobility-services/testingsanty', 'serverless-shell-scripts/.']

  # Push the image to GCR.IO.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/global-mobility-services/testingsanty']

  # Create the Cloud Run service.
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'my-service'
    - '--image'
    - 'gcr.io/global-mobility-services/testingsanty:latest'
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-central1'
    - '--port'
    - '8080'
    - '--allow-unauthenticated'
  # creating the cloud -scheduler 
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
    - 'CLOUD_RUN_URL=$(gcloud beta run services describe my-service --platform managed --region us-central1 --format="value(status.url)")'
    args:
    - 'beta'
    - 'scheduler'
    - 'jobs'
    - 'create'
    - 'http'
    - 'my-job'
    - '--schedule'
    - '0 */12 * * *'
    - '--time-zone'
    - 'EET'
    - '--uri'
    - '$CLOUD_RUN_URL'
    - '--http-method'
    - 'POST'
    - '--min-backoff'
    - '6h'
    - '--max-backoff'
    - '6h'
    - '--max-doublings'
    - '5'
    - '--attempt-deadline'
    - '30m'
