steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - SERVICE_NAME
      - --image=gcr.io/global-mobility-services/testingsanty:latest
      - --platform=managed
      - --region=us-central1
      - --allow-unauthenticated
      - --port=8080
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - beta
      - scheduler
      - jobs
      - create
      - http
      - job-2
      - --schedule="0 0/12 * * *"
      - --time-zone="EET"
      - --uri=${CLOUD_RUN_URL}
      - --http-method=POST
      - --min-backoff=6h
      - --max-backoff=6h
      - --max-doublings=5
      - --attempt-deadline=30m
substitutions:
  CLOUD_RUN_URL: "https://$(gcloud run services describe --format='value(status.url)' --platform managed SERVICE_NAME --region us-central1)"
  SERVICE_NAME: testing-2
  PROJECT_ID: global-mobility-services
